var srcIndex = JSON.parse('{\
"argmin":["",[["core",[["checkpointing",[],["mod.rs"]],["observers",[],["mod.rs"]],["state",[],["iterstate.rs","linearprogramstate.rs","mod.rs","populationstate.rs"]]],["errors.rs","executor.rs","float.rs","kv.rs","macros.rs","mod.rs","parallelization.rs","problem.rs","result.rs","solver.rs","termination.rs","test_utils.rs"]],["solver",[["brent",[],["brentopt.rs","brentroot.rs","mod.rs"]],["conjugategradient",[],["beta.rs","cg.rs","mod.rs","nonlinear_cg.rs"]],["gaussnewton",[],["gaussnewton_linesearch.rs","gaussnewton_method.rs","mod.rs"]],["goldensectionsearch",[],["mod.rs"]],["gradientdescent",[],["mod.rs","steepestdescent.rs"]],["landweber",[],["mod.rs"]],["linesearch",[["condition",[],["armijo.rs","goldstein.rs","mod.rs","strongwolfe.rs","wolfe.rs"]]],["backtracking.rs","hagerzhang.rs","mod.rs","morethuente.rs"]],["neldermead",[],["mod.rs"]],["newton",[],["mod.rs","newton_cg.rs","newton_method.rs"]],["particleswarm",[],["mod.rs"]],["quasinewton",[],["bfgs.rs","dfp.rs","lbfgs.rs","mod.rs","sr1.rs","sr1_trustregion.rs"]],["simulatedannealing",[],["mod.rs"]],["trustregion",[],["cauchypoint.rs","dogleg.rs","mod.rs","steihaug.rs","trustregion_method.rs"]]],["mod.rs"]]],["lib.rs"]],\
"argmin_checkpointing_file":["",[],["lib.rs"]],\
"argmin_math":["",[["nalgebra_m",[],["add.rs","conj.rs","div.rs","dot.rs","eye.rs","inv.rs","l1norm.rs","l2norm.rs","minmax.rs","mod.rs","mul.rs","random.rs","scaledadd.rs","scaledsub.rs","signum.rs","sub.rs","transpose.rs","zero.rs"]],["ndarray_m",[],["add.rs","conj.rs","div.rs","dot.rs","eye.rs","inv.rs","l1norm.rs","l2norm.rs","minmax.rs","mod.rs","mul.rs","random.rs","scaledadd.rs","scaledsub.rs","signum.rs","sub.rs","transpose.rs","zero.rs"]],["primitives",[],["add.rs","conj.rs","div.rs","dot.rs","l1norm.rs","l2norm.rs","mod.rs","mul.rs","random.rs","scaledadd.rs","scaledsub.rs","sub.rs","transpose.rs","weighteddot.rs","zero.rs"]],["vec",[],["add.rs","conj.rs","div.rs","dot.rs","eye.rs","l1norm.rs","l2norm.rs","minmax.rs","mod.rs","mul.rs","random.rs","scaledadd.rs","scaledsub.rs","signum.rs","sub.rs","transpose.rs","zero.rs"]]],["lib.rs"]],\
"argmin_observer_paramwriter":["",[],["lib.rs"]],\
"argmin_observer_slog":["",[],["lib.rs"]],\
"argmin_observer_spectator":["",[],["lib.rs","observer.rs","sender.rs"]],\
"example_backtracking":["",[],["main.rs"]],\
"example_bfgs":["",[],["main.rs"]],\
"example_brentopt":["",[],["main.rs"]],\
"example_brentroot":["",[],["main.rs"]],\
"example_checkpoint":["",[],["main.rs"]],\
"example_conjugategradient":["",[],["main.rs"]],\
"example_dfp":["",[],["main.rs"]],\
"example_gaussnewton":["",[],["main.rs"]],\
"example_gaussnewton_linesearch":["",[],["main.rs"]],\
"example_gaussnewton_nalgebra":["",[],["main.rs"]],\
"example_goldensectionsearch":["",[],["main.rs"]],\
"example_hagerzhang":["",[],["main.rs"]],\
"example_landweber":["",[],["main.rs"]],\
"example_lbfgs":["",[],["main.rs"]],\
"example_lbfgs_nalgebra":["",[],["main.rs"]],\
"example_morethuente":["",[],["main.rs"]],\
"example_neldermead":["",[],["main.rs"]],\
"example_neldermead_cubic":["",[],["main.rs"]],\
"example_newton":["",[],["main.rs"]],\
"example_newton_cg":["",[],["main.rs"]],\
"example_nonlinear_cg":["",[],["main.rs"]],\
"example_observer":["",[],["main.rs"]],\
"example_owl_qn":["",[],["main.rs"]],\
"example_particleswarm":["",[],["main.rs"]],\
"example_particlswarm_nalgebra":["",[],["main.rs"]],\
"example_simulatedannealing":["",[],["main.rs"]],\
"example_spectator_basic":["",[],["main.rs"]],\
"example_spectator_multiple":["",[],["main.rs"]],\
"example_sr1":["",[],["main.rs"]],\
"example_sr1_trustregion":["",[],["main.rs"]],\
"example_steepestdescent":["",[],["main.rs"]],\
"example_steepestdescent_manifold":["",[],["main.rs"]],\
"example_timeout":["",[],["main.rs"]],\
"example_trustregion":["",[],["main.rs"]],\
"spectator":["",[],["lib.rs","message.rs"]]\
}');
createSrcSidebar();
