version: 2

jobs:
  lint:
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            rustup component add rustfmt
            rustup component add clippy
      - run:
          name: cargo fmt
          command: |
            cargo fmt -- --check
      - run:
          name: cargo clippy
          command: |
            cargo clippy --all-features --all-targets -- -D warnings || true


workflows:
  version: 2
  build:
    jobs:
      - lint
