[package]
name = "example-steepestdescent_manifold"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
argmin = { version = "*", path = "../../argmin" }
argmin-math = { version = "*", default-features = false, path = "../../argmin-math" }
argmin-observer-slog = { version = "*", path = "../../observers/slog/" }
serde = { version = "1.0.195", features = ["derive"] }
