[package]
name = "argmin-observer-egui"
version = "0.1.0"
authors = ["Stefan Kroboth <stefan.kroboth@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "egui observer for argmin"
documentation = "https://docs.rs/argmin_observer_egui/"
homepage = "https://argmin-rs.org"
repository = "https://github.com/argmin-rs/argmin"
readme = "README.md"
keywords = ["optimization", "math", "science"]
categories = ["science"]
exclude = []

# [[bin]]
# name = "argmin-plotter"
# path = "src/main.rs"

[dependencies]
anyhow = "1.0"
argmin = { version = "0.8.0", path = "../../argmin", default-features = false, features = ["serde1"] }
bincode = "1.3.3"
bytes = "1.4.0"
dashmap = { version = "5.4.0", features = ["serde"] }
eframe = { version = "0.20", features = ["ron", "persistence"] }
egui_dock = "0.3.1"
egui_extras = "0.20.0"
futures = "0.3.26"
itertools = "0.10.5"
pot = "1.0.2"
procspawn = "0.10.2"
rmp-serde = "1.1.1"
serde = { version = "1.0.152", features = ["derive"] }
time = { version = "0.3.17", features = ["serde"] }
tokio = { version = "1.25.0", features = ["full", "sync"] }
tokio-stream = "0.1.11"
tokio-util = { version = "0.7.5", features = ["codec"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-bunyan-formatter = "0.3.6"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["registry", "env-filter"] }
uuid = { version = "1.3.0", features = ["v4"] }

[dev-dependencies]
argmin_testfunctions = "0.1.1"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
