[package]
name = "ndarray_0_15"
version = "0.0.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
argmin-math = { path = "../../", version = "*", features = [
    "ndarray_v0_15",
] }
ndarray = { version = "0.15", default-features = false }
ndarray-linalg = { version = "0.16", default-features = false, features = ["intel-mkl-static"] }
num-complex = { version = "0.4", default-features = false }
num-traits = { version = "0.2", default-features = false }
num-integer = { version = "0.1", default-features = false }
paste = "1"
approx = "0.5.0"
rand = "*" # Should unify with whatever is currently used in argmin itself

[features]

# To make it explicit that this package is not part of the overall argmin workspace for the purpose of dependency unification
[workspace]
