name: argmin book

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
jobs:
  book:
    name: Book test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Generate harness
        working-directory: ./docs/book/tests
        run: ./generate_book_tests.sh

      - name: Test code samples
        working-directory: ./docs/book/tests
        run: cargo test
